"""Chat API routes."""
from datetime import datetime
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status

from app.api.mock_data import MOCK_CHATS, MOCK_MESSAGES
from app.api.schemas import MessageCreate, MessageResponse
from app.middleware.auth import get_current_user
from app.models import User

router = APIRouter()

# In-memory counter for new message IDs
_message_id_counter = 100


@router.get("")
def get_chats(current_user: User = Depends(get_current_user)) -> list[dict[str, Any]]:
    """Get all chats for the current user."""
    # In mock mode, return all chats
    # In real mode, filter by user_id
    return MOCK_CHATS


@router.get("/{chat_id}")
def get_chat(
    chat_id: int,
    current_user: User = Depends(get_current_user),
) -> dict[str, Any]:
    """Get a specific chat with its messages."""
    # Find chat
    chat = next((c for c in MOCK_CHATS if c["id"] == chat_id), None)
    
    if not chat:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat not found",
        )
    
    # Get messages for this chat
    messages = MOCK_MESSAGES.get(chat_id, [])
    
    return {
        **chat,
        "messages": messages,
    }


@router.post("/{chat_id}/messages", response_model=MessageResponse, status_code=status.HTTP_201_CREATED)
def create_message(
    chat_id: int,
    message: MessageCreate,
    current_user: User = Depends(get_current_user),
) -> MessageResponse:
    """Create a new message in a chat (user or AI)."""
    global _message_id_counter
    
    # Check if chat exists
    chat = next((c for c in MOCK_CHATS if c["id"] == chat_id), None)
    if not chat:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Chat not found",
        )
    
    # Create new message
    new_message = {
        "id": _message_id_counter,
        "chat_id": chat_id,
        "sender_id": current_user.id if message.sender_type == "user" else None,
        "sender_type": message.sender_type,
        "content": message.content,
        "thinking": [],
        "action": None,
        "drawer_data": None,
        "created_at": datetime.utcnow().isoformat(),
    }
    
    _message_id_counter += 1
    
    # Add to mock messages
    if chat_id not in MOCK_MESSAGES:
        MOCK_MESSAGES[chat_id] = []
    MOCK_MESSAGES[chat_id].append(new_message)
    
    # If user message, generate a mock AI response
    if message.sender_type == "user":
        ai_response = {
            "id": _message_id_counter,
            "chat_id": chat_id,
            "sender_id": None,
            "sender_type": "ai",
            "content": f"I understand you're asking about: '{message.content}'. This is a mock response. In production, this would be generated by the AI Broker.",
            "thinking": [
                "Processing your request",
                "Analyzing context",
                "Generating response",
            ],
            "action": None,
            "drawer_data": None,
            "created_at": datetime.utcnow().isoformat(),
        }
        _message_id_counter += 1
        MOCK_MESSAGES[chat_id].append(ai_response)
    
    return MessageResponse(**new_message)

